{"company": "A I Cotton Industries", "records": [{"size": "Long Term Bank Loan - 14 Crore", "rating": "BWR B +", "outlook": "Stable"}]}
{"company": "A Infrastructure Limited", "records": [{"size": "Long Term Bank Loan - 48.40 Crore", "rating": "BWR BBB -", "outlook": "Stable"}, {"size": "Short Term Bank Loan - 45 Crore", "rating": "BWR A3", "outlook": ""}]}
{"company": "A K Infraprojects Pvt. Ltd", "records": [{"size": "Long Term Bank Loan - 4.50 Crore", "rating": "BWR B +", "outlook": "Stable"}, {"size": "Short Term Bank Loan - 15 Crore", "rating": "BWR A4", "outlook": ""}]}
{"company": "A K Soni Hosiery Mills Pvt. Ltd", "records": [{"size": "Long Term Bank Loan - 20.47 Crore", "rating": "BWR D&lt;br/&gt;Issuer did not Co-operate; Based on best available information.", "outlook": ""}]}
{"company": "A K Stockmart Pvt. Ltd", "records": [{"size": "Long Term Bank Loan - 20 Crore", "rating": "BWR A", "outlook": "Stable"}]}
{"company": "A L Overseas", "records": [{"size": "Long Term Bank Loan - 15 Crore", "rating": "BWR BB -&lt;br/&gt;Issuer did not Co-operate; Based on best available information.", "outlook": "Stable"}]}
{"company": "A M Exports", "records": [{"size": "Short Term Bank Loan - 17.70 Crore", "rating": "BWR A4 +&lt;br/&gt; (Not Reviewed)", "outlook": ""}]}
{"company": "A S Wire Industries (VSP) Pvt. Ltd.", "records": [{"size": "Long Term Bank Loan - 10.63 Crore", "rating": "BWR B +", "outlook": "Stable"}]}
{"company": "A -Tex Home Collection", "records": [{"size": "Long Term Bank Loan - 1.03 Crore", "rating": "BWR B +", "outlook": "Stable"}, {"size": "Short Term Bank Loan - 10 Crore", "rating": "BWR A4", "outlook": ""}]}
{"company": "A. N. Enterprise", "records": [{"size": "Long Term Bank Loan - 5 Crore", "rating": "BWR BB -&lt;br/&gt;Issuer did not Co-operate; Based on best available information.", "outlook": "Stable"}, {"size": "Short Term Bank Loan - 1.50 Crore", "rating": "BWR A4&lt;br/&gt;Issuer did not Co-operate; Based on best available information.", "outlook": ""}]}
{"company": "A.A Estate Pvt. Ltd.", "records": [{"size": "Proposed Secured Non Convertible Debentures -  148 Crore", "rating": "Rating Withdrawn", "outlook": ""}, {"size": "Proposed Secured Non Convertible Debentures - 20 Crore", "rating": "Rating Withdrawn", "outlook": ""}]}
{"company": "A.K. Power Industries Pvt. Ltd.", "records": [{"size": "Long Term Bank Loan - 84.10 Crore", "rating": "BWR D&lt;br/&gt; (Not Reviewed)", "outlook": ""}, {"size": "Short Term Bank Loan - 15.20 Crore", "rating": "BWR D&lt;br/&gt; (Not Reviewed)", "outlook": ""}]}
{"company": "A.S. Enterprise", "records": [{"size": "Short Term Bank Loan - 17 Crore (Enhanced from Rs. 15Cr)", "rating": "BWR A4 +", "outlook": ""}]}
{"company": "A.S. Patel", "records": [{"size": "Long Term Bank Loan - 4 Crore", "rating": "BWR BB -", "outlook": "Stable"}, {"size": "Short Term Bank Loan - 17 Crore", "rating": "BWR A4", "outlook": ""}]}
{"company": "A.V. Cam Corporation", "records": [{"size": "Long Term Bank Loan - 7.46 Crore", "rating": "BWR B -&lt;br/&gt;Issuer did not Co-operate; Based on best available information.", "outlook": "Stable"}, {"size": "Short Term Bank Loan - 0.15 Crore", "rating": "BWR A4&lt;br/&gt;Issuer did not Co-operate; Based on best available information.", "outlook": ""}]}
{"company": "A2Z Autowheels Pvt Ltd", "records": [{"size": "Long Term Bank Loan - 20.75 Crore", "rating": "BWR BB&lt;br/&gt; (Not Reviewed)", "outlook": "Stable"}]}
{"company": "AAA Paper Marketing Ltd.", "records": [{"size": "Long Term Bank Loan - 28.50 Crore(enhanced from Rs.23 Cr)", "rating": "BWR BB -&lt;br/&gt; (Not Reviewed)", "outlook": "Stable"}, {"size": "Short Term Bank Loan - 12 Crore (LC is the sub-limit of CC)", "rating": "BWR A4&lt;br/&gt; (Not Reviewed)", "outlook": ""}]}
{"company": "Aabhas Spinners (Pvt) Ltd.", "records": [{"size": "Long Term Bank Loan - 4.75 Crore", "rating": "BWR B +", "outlook": "Stable"}, {"size": "Short Term Bank Loan - 0.20 Crore", "rating": "BWR A4", "outlook": ""}]}
{"company": "Aadarsh Private Limited", "records": [{"size": "Long Term Bank Loan - 7 Crore", "rating": "BWR BB -&lt;br/&gt; (Not Reviewed)", "outlook": "Stable"}, {"size": "Short Term Bank Loan - 3.50 Crore", "rating": "BWR A4&lt;br/&gt; (Not Reviewed)", "outlook": ""}]}
{"company": "Aadhan Builders LLP", "records": [{"size": "Long Term Bank Loan - 50 Crore", "rating": "BWR BB +", "outlook": "Stable"}]}
{"company": "Aadhar Housing Finance Limited (erstwhileDHFL Vysya Housing Finance Ltd)", "records": [{"size": "Secured Non Convertible Debentures - 900 Crore", "rating": "BWR AA + (SO)", "outlook": "Stable"}, {"size": "Secured Non Convertible Debentures - 150 Crore", "rating": "BWR AA + (SO)", "outlook": "Stable"}, {"size": "Proposed Secured Non Convertible Debentures - 3000 Crore", "rating": "BWR AA + (SO)", "outlook": "Stable"}]}
{"company": "Aadhar Housing Finance Ltd.", "records": [{"size": "UnSecured Non Convertible Debentures - 150 Crore", "rating": "Rating Withdrawn", "outlook": ""}, {"size": "Proposed Secured Non Convertible Debentures - 300 Crore", "rating": "Rating Withdrawn", "outlook": ""}, {"size": "Secured Non Convertible Debentures - 50 Crore", "rating": "Rating Withdrawn", "outlook": ""}, {"size": "Secured Non Convertible Debentures - 50 Crore", "rating": "Rating Withdrawn", "outlook": ""}, {"size": "Secured Non Convertible Debentures - 100 Crore", "rating": "Rating Withdrawn", "outlook": ""}, {"size": "Secured Non Convertible Debentures - 100 Crore", "rating": "Rating Withdrawn", "outlook": ""}]}
